version: 2
updates:
- package-ecosystem: gradle
  directory: "/"
  schedule:
    interval: daily
    time: "04:00"
  open-pull-requests-limit: 10
  ignore:
  - dependency-name: org.codehaus.groovy:groovy-all
    versions:
    - 3.0.7
  - dependency-name: org.apache.jena:jena-core
    versions:
    - 3.17.0
  - dependency-name: junit:junit
    versions:
    - 4.13.1
